use sc_db;

-- Monetary Values
SELECT 
COUNT(*) AS NUM_OF_ORDERS,
ROUND(SUM(SALES),2) AS REVENUE_TOTAL,
ROUND(SUM(PROFIT),2) AS TOTAL_PROFIT,
ROUND(AVG(SALES),2) AS AVERAGE_ORDER_VALUE
FROM ORDERS;

-- Top 5 States by Total_Revuene
SELECT 
C.STATE AS STATE,
ROUND(SUM(O.SALES),2) AS TOTAL_REVENUE
FROM ORDERS O
JOIN CUSTOMERS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.STATE
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;

-- Which product categories generate the highest revenue and profit?
SELECT 
P.CATEGORY AS CATEGORY,
ROUND(SUM(O.SALES),2) AS TOTAL_REVENUE,
ROUND(SUM(O.PROFIT),2) AS TOTAL_PROFIT
FROM ORDERS O
JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY 2 DESC,3 DESC
;

-- Which warehouses are experiencing the most late deliveries?
SELECT 
W.WAREHOUSE_NAME AS WAREHOUSE,
COUNT(*) AS LATE_DELIVERIES
FROM ORDERS O
JOIN WAREHOUSES W
ON O.WAREHOUSE_ID = W.WAREHOUSE_ID
WHERE O.DELIVERY_STATUS = "Late"
GROUP BY WAREHOUSE
ORDER BY 2 DESC
;

-- average delivery time by shipping mode
SELECT 
O.SHIPPING_MODE AS SHIPPING_MODE,
ROUND(AVG(L.ACTUAL_DELIVERY_DAYS),2) AS AVERAGE_DELIVERY_DAYS
FROM ORDERS O 
JOIN LOGISTICS L
ON O.ORDER_ID = L.ORDER_ID
GROUP BY O.SHIPPING_MODE
ORDER BY AVERAGE_DELIVERY_DAYS ASC;

-- average delivery time by REGION
SELECT 
C.REGION AS REGION,
ROUND(AVG(L.ACTUAL_DELIVERY_DAYS),2) AS AVERAGE_DELIVERY_DAYS
FROM ORDERS O 
JOIN CUSTOMERS C 
ON O.CUSTOMER_ID = C.CUSTOMER_ID
JOIN LOGISTICS L ON O.ORDER_ID = L.ORDER_ID
GROUP BY C.REGION
ORDER BY AVERAGE_DELIVERY_DAYS ASC;

-- On-Time Delivery Performance
SELECT * FROM ORDERS;
SELECT 
DELIVERY_STATUS,
COUNT(*) AS TOTAL_ORDERS,
ROUND((COUNT(*) / (SELECT COUNT(*) FROM ORDERS))*100,2) AS ON_TIME_DELIVER_PERFORMANCE
FROM ORDERS
GROUP BY  DELIVERY_STATUS;

-- Find the return rate (%) for each product category.
SELECT 
P.CATEGORY AS CATEGORY,
COUNT(O.PRODUCT_ID) AS TOTAL_ORDERS,
COUNT(R.RETURN_ID) AS TOTAL_RETURNS,
ROUND((COUNT(R.RETURN_ID)/COUNT(O.ORDER_ID)) *100, 2) AS 'RETURN RATE %'
FROM ORDERS O 
JOIN PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN RETURNS R ON R.ORDER_ID = O.ORDER_ID
GROUP BY P.CATEGORY
;

-- Which shipping mode is the fastest and which one is the most expensive?
SELECT 
O.SHIPPING_MODE AS SHIPPING_MODE,
COUNT(*) AS TOTAL_ORDERS,
ROUND(AVG(SHIPPING_COST),2) AS AVG_SHIPPING_COST,
ROUND(AVG(ACTUAL_DELIVERY_DAYS),2) AS AVG_DELIVER_DAYS
FROM ORDERS O
JOIN LOGISTICS L
ON O.ORDER_ID = L.ORDER_ID
GROUP BY O.SHIPPING_MODE
ORDER BY AVG_DELIVER_DAYS 
;
 
-- Business Case #1 - Customer Lifetime Value (CLV)
SELECT 
C.CUSTOMER_ID AS CUSTOMER_ID,
C.CUSTOMER_NAME AS CUSTOMER_NAME,
COUNT(O.ORDER_ID) AS NUM_OF_ORDERS,
ROUND(SUM(O.SALES),2) AS TOTAL_REVENUE,
ROUND(SUM(O.PROFIT),2) AS TOTAL_PROFIT,
ROUND(AVG(O.SALES),2) AS AVERAGE_ORDER_VALUE
FROM ORDERS O 
JOIN CUSTOMERS C 
ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
;

/* 	CUSTOMER 395 HAS REVENUE OF 1,79,140.33 AND PROFIT OF 53,279.33 WHEREAS 
	CUSTOMER 184 HAS REVENUE OF 1,65,934.02 AND PROFIT OF 56,949.02 . 
    Customer 395 generated the highest revenue, making them the largest revenue contributor among the two. 
    However, Customer 184 generated a higher profit despite lower revenue, indicating their purchases were more profitable. 
    Depending on the company's objective, revenue growth or profit maximization, either customer could be considered more valuable.
*/

-- Business Case #2 – Pareto Analysis (80/20 Rule)
/* Scenario
	I've heard that about 20% of customers generate around 80% of revenue. Can you verify whether that's true for our business?
*/
WITH REVENUE_PER_CUSTOMER AS 
(
SELECT 
C.CUSTOMER_NAME AS CUSTOMER_NAME,
ROUND(SUM(O.SALES),2) AS REVENUE
FROM ORDERS O
JOIN CUSTOMERS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
),

CUMMULATIVE_REVENUE AS 
(
SELECT 
CUSTOMER_NAME,
REVENUE,
SUM(REVENUE) OVER (ORDER BY REVENUE DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMMULATIVE_REVENUE
FROM REVENUE_PER_CUSTOMER
),

CUMMULATIVE_PERCENTAGE AS (
SELECT 
CUSTOMER_NAME,
REVENUE,
CUMMULATIVE_REVENUE,
ROUND((CUMMULATIVE_REVENUE / (SELECT SUM(SALES) FROM ORDERS) * 100),2) AS PARETO_PERCENTAGE
FROM CUMMULATIVE_REVENUE)

SELECT 
COUNT(*) AS NUM_OF_CUSTOMERS
FROM CUMMULATIVE_PERCENTAGE
WHERE PARETO_PERCENTAGE <= 80;

/* 
Instead of 20% of customers contributing 80% of revenue, almost 60% of customers are needed to reach 80% of the revenue.

What does this tell us?
Revenue is fairly distributed among customers.
The business is not heavily dependent on a small group of customers.
Losing one or two customers would have less impact than in a business where revenue is concentrated among a few key customers.
Marketing and retention efforts should target a broader customer base rather than focusing only on a handful of high-value customers.
*/

-- Business Case #3 – RFM Analysis
/* Scenario
"We want to identify our best customers and customers who are at risk of leaving.

Please segment all customers based on:
How recently they purchased
How frequently they purchase
How much money they spend."
*/
WITH RFM_CAL AS 
(
SELECT 
C.CUSTOMER_NAME AS CUSTOMER,
MAX(O.ORDER_DATE) AS LAST_ORDER_DATE,
DATEDIFF((SELECT MAX(ORDER_DATE) FROM ORDERS), MAX(O.ORDER_DATE)) AS RECENCY,  #DATEDIFF(DATASET LAST ORDER DATE, CUSTOMER LAST ORDER DATE)
COUNT(*) AS FREQUENCY, #NUMBER OF ORDERS
SUM(O.SALES) AS MONETARY
FROM CUSTOMERS C
JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME),

RFM_SCORE AS 
(
SELECT 
CUSTOMER,
RECENCY,
FREQUENCY,
MONETARY,
NTILE(5) OVER (ORDER BY RECENCY DESC) AS R,
NTILE(5) OVER (ORDER BY FREQUENCY ASC) AS F,
NTILE(5) OVER (ORDER BY MONETARY ASC) AS M
FROM RFM_CAL
)

#CUSTOMER SEGMENTATION
SELECT 
CUSTOMER,
R,
F,
M,
CASE 
	WHEN R>=4 AND F>=4 AND M>= 4 THEN 'CHAMPION CUSTOMER'
    WHEN R>=4 AND F>=4 THEN 'LOYAL CUSTOMER'
    WHEN R>=4 THEN 'RECENT CUSTOMER'
    WHEN M>=4 THEN 'BIG SPENDER CUSTOMER' 
    WHEN R<=2 AND F<=2  THEN 'AT RISK CUSTOMER'
    ELSE 'REGULAR CUSTOMER'
END AS CUSTOMER_SEGMENT
FROM  RFM_SCORE
;

-- Inventory Optimization

-- We've got thousands of products. I don't know which ones deserve my attention. Can you help?
-- Which products are our fastest-moving products?
SELECT 
P.PRODUCT_ID AS PRODUCT_ID,
P.PRODUCT_NAME AS PRODUCT_NAME,
P.CATEGORY AS CATEGORY,
SUM(O.QUANTITY) AS TOTAL_QUANTITY_SOLD 
FROM PRODUCTS P 
JOIN ORDERS O 
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY
ORDER BY TOTAL_QUANTITY_SOLD DESC
;

-- "Some products are sitting in our warehouses for months. They aren't selling. I want to know which products are our slow-moving or dead-stock items."
SELECT 
P.PRODUCT_ID AS PRODUCT_ID,
P.PRODUCT_NAME AS PRODUCT_NAME,
P.CATEGORY AS CATEGORY,
SUM(O.QUANTITY) AS TOTAL_QUANTITY_SOLD 
FROM PRODUCTS P 
JOIN ORDERS O 
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY
ORDER BY TOTAL_QUANTITY_SOLD ASC
LIMIT 10
;

-- "I don't just want the fastest-selling products. I want to know which products contribute the most to our revenue so that we can prioritize inventory investment."
-- ABC INVENTORY CLASSIFICATION
WITH REVENUE_CONTRIBUTION AS (
SELECT 
P.PRODUCT_ID AS PRODUCT_ID,
P.PRODUCT_NAME AS PRODUCT_NAME,
P.CATEGORY AS CATEGORY,
ROUND(SUM(O.SALES),2) AS TOTAL_REVENUE
FROM PRODUCTS P 
JOIN ORDERS O 
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY
),

REVENUE_PERCENTAGE AS (
SELECT 
PRODUCT_ID,
PRODUCT_NAME,
CATEGORY,
TOTAL_REVENUE,
 ROUND(( TOTAL_REVENUE/ SUM(TOTAL_REVENUE) OVER () )* 100,2)  AS REVENUE_PERC
FROM REVENUE_CONTRIBUTION
),

CUMMULATIVE_REVENUE_PERC AS (
SELECT 
PRODUCT_ID,
PRODUCT_NAME,
CATEGORY,
TOTAL_REVENUE,
REVENUE_PERC,
SUM(REVENUE_PERC) OVER (ORDER BY TOTAL_REVENUE DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMMULATIVE_REVENUE_PERCENATGE
FROM REVENUE_PERCENTAGE
)

SELECT *,
CASE 
	WHEN CUMMULATIVE_REVENUE_PERCENATGE <= 80 THEN 'A'   #TOP 80% REVENUE CONTRIBUTION BY PRODUCTS
    WHEN CUMMULATIVE_REVENUE_PERCENATGE > 80 AND CUMMULATIVE_REVENUE_PERCENATGE <= 95 THEN 'B' #REST 15% REVENUE CONTRIBUTION BY PRODUCTS
    ELSE 'C' #REST 5% REVENUE CONTRIBUTION BY PRODUCTS
    END AS ABC_CATEGORY
    FROM CUMMULATIVE_REVENUE_PERC ;

# WAREHOUSE ANALYTICS

-- Which warehouse is performing the best?
/* 
Which warehouse generates the highest revenue?	
Which warehouse processes the most orders?	
Which warehouse is the most profitable?	
Which warehouse has the highest return rate?	
Which warehouse has the fastest delivery performance?	
Warehouse Performance Scorecard
*/

-- Which warehouse generates the highest revenue?
WITH REVENUE_CTE AS (
SELECT 
W.WAREHOUSE_ID AS WAREHOUSE_ID,
W.WAREHOUSE_NAME AS WAREHOUSE_NAME,
W.REGION AS REGION,
ROUND(SUM(O.SALES),2) AS REVENUE
FROM WAREHOUSES W
JOIN ORDERS O
ON W.WAREHOUSE_ID = O.WAREHOUSE_ID
GROUP BY W.WAREHOUSE_ID,
W.WAREHOUSE_NAME,
W.REGION
),

-- Which warehouse processes the most orders?	
MOST_ORDERS_CTE AS (
SELECT 
W.WAREHOUSE_ID AS WAREHOUSE_ID,
W.WAREHOUSE_NAME AS WAREHOUSE_NAME,
W.REGION AS REGION,
COUNT(*) AS MOST_ORDERS
FROM WAREHOUSES W
JOIN ORDERS O
ON W.WAREHOUSE_ID = O.WAREHOUSE_ID
GROUP BY W.WAREHOUSE_ID,
W.WAREHOUSE_NAME,
W.REGION
),


-- Which warehouse is the most profitable?	
PROFIT_CTE AS (
SELECT 
W.WAREHOUSE_ID AS WAREHOUSE_ID,
W.WAREHOUSE_NAME AS WAREHOUSE_NAME,
W.REGION AS REGION,
ROUND(SUM(O.PROFIT),2) AS PROFIT
FROM WAREHOUSES W
JOIN ORDERS O
ON W.WAREHOUSE_ID = O.WAREHOUSE_ID
GROUP BY W.WAREHOUSE_ID,
W.WAREHOUSE_NAME,
W.REGION
),


-- Which warehouse has the highest return rate?
RETURN_RATE_CTE AS (
SELECT 
W.WAREHOUSE_ID AS WAREHOUSE_ID,
W.WAREHOUSE_NAME AS WAREHOUSE_NAME,
W.REGION AS REGION,
ROUND((COUNT(R.RETURN_ID) / COUNT(DISTINCT O.ORDER_ID)) * 100,2) AS RETURN_RATE
FROM ORDERS O
JOIN WAREHOUSES W ON O.WAREHOUSE_ID = W.WAREHOUSE_ID
LEFT JOIN RETURNS R ON O.ORDER_ID = R.ORDER_ID
GROUP BY W.WAREHOUSE_ID,
W.WAREHOUSE_NAME,
W.REGION
),

-- Which warehouse has the fastest delivery performance?
ON_TIME_DELIVERY_RATE_CTE AS (
SELECT 
W.WAREHOUSE_ID AS WAREHOUSE_ID,
W.WAREHOUSE_NAME AS WAREHOUSE_NAME,
W.REGION AS REGION,
ROUND((COUNT(CASE WHEN O.DELIVERY_STATUS = 'ON TIME' THEN DELIVERY_STATUS END) / COUNT(O.ORDER_ID) )*100,2) AS ON_TIME_DELIVERY_RATE
FROM ORDERS O
JOIN WAREHOUSES W ON O.WAREHOUSE_ID = W.WAREHOUSE_ID
GROUP BY W.WAREHOUSE_ID,
W.WAREHOUSE_NAME,
W.REGION
)

-- Warehouse Performance Scorecard

SELECT 
RC.WAREHOUSE_ID AS WAREHOUSE_ID,
RC.WAREHOUSE_NAME AS WAREHOUSE_NAME,
RC.REGION AS REGION,
RC.REVENUE AS REVENUE,
MOC.MOST_ORDERS AS MOST_ORDERS,
PC.PROFIT AS PROFIT,
RRC.RETURN_RATE AS RETURN_RATE,
OTDRC.ON_TIME_DELIVERY_RATE AS ON_TIME_DELIVERY_RATE
FROM REVENUE_CTE RC
JOIN MOST_ORDERS_CTE MOC ON RC.WAREHOUSE_ID = MOC.WAREHOUSE_ID
JOIN PROFIT_CTE PC ON RC.WAREHOUSE_ID = PC.WAREHOUSE_ID
JOIN RETURN_RATE_CTE RRC ON RC.WAREHOUSE_ID = RRC.WAREHOUSE_ID
JOIN ON_TIME_DELIVERY_RATE_CTE OTDRC ON RC.WAREHOUSE_ID = OTDRC.WAREHOUSE_ID
ORDER BY WAREHOUSE_ID ASC
;

-- Profitability Analysis
-- Show me the products that are actually losing us money.
SELECT 
P.PRODUCT_ID AS PRODUCT_ID,
P.PRODUCT_NAME AS PRODUCT_NAME,
P.CATEGORY AS CATEGORY,
ROUND(SUM(O.SALES),2) AS TOTAL_REVENUE,
ROUND(SUM(O.PROFIT),2) AS TOTAL_PROFIT
FROM PRODUCTS P
JOIN ORDERS O 
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_ID,
PRODUCT_NAME,
CATEGORY
HAVING TOTAL_PROFIT < 0
ORDER BY TOTAL_PROFIT DESC;

-- I don't want to know which category earns the most revenue.I want to know which category is the most profitable.
SELECT 
P.CATEGORY AS CATEGORY,
ROUND(SUM(O.SALES),2) AS TOTAL_REVENUE,
ROUND(SUM(O.PROFIT),2) AS TOTAL_PROFIT,
ROUND((SUM(O.PROFIT)/SUM(O.SALES)) * 100,2) AS PROFIT_MARGIN
FROM PRODUCTS P
JOIN ORDERS O 
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY CATEGORY
ORDER BY PROFIT_MARGIN DESC;

-- Find products that have High Revenue but Low Profit
WITH PRODUCT_CONTRIBUTION AS (
SELECT P.PRODUCT_ID AS PRODUCT_ID,
P.PRODUCT_NAME AS PRODUCT_NAME,
ROUND(SUM(O.SALES),2) AS TOTAL_REVENUE,
ROUND(SUM(O.PROFIT),2) AS TOTAL_PROFIT,
ROUND((SUM(O.PROFIT)/SUM(O.SALES)) * 100,2) AS PROFIT_MARGIN
FROM PRODUCTS P
JOIN ORDERS O 
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_ID,
PRODUCT_NAME),

PRODUCT_QUARTILES AS 
(
SELECT
PRODUCT_ID,
PRODUCT_NAME,
TOTAL_REVENUE,
TOTAL_PROFIT,
PROFIT_MARGIN,
NTILE(4) OVER (ORDER BY TOTAL_REVENUE DESC) AS HIGH_REVENUE,
NTILE(4) OVER (ORDER BY TOTAL_PROFIT ASC) AS LOW_PROFIT
FROM PRODUCT_CONTRIBUTION
)

SELECT 
*
FROM PRODUCT_QUARTILES
WHERE HIGH_REVENUE = 1 AND LOW_PROFIT = 1
;

-- Which regions contribute the most profit to NovaCart?
SELECT 
C.REGION AS REGION,
ROUND(SUM(O.SALES),2) AS TOTAL_REVENUE,
ROUND(SUM(O.PROFIT),2) AS TOTAL_PROFIT,
ROUND((SUM(O.PROFIT)/SUM(O.SALES)) * 100,2) AS PROFIT_MARGIN
FROM CUSTOMERS C
JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.REGION
ORDER BY TOTAL_PROFIT DESC;

-- "Stop sending me separate reports. Give me one executive summary."
WITH CATEGORY_CONTRIBUTION AS (
SELECT 
P.CATEGORY AS CATEGORY,
ROUND(SUM(O.SALES),2) AS TOTAL_REVENUE,
ROUND(SUM(O.PROFIT),2) AS TOTAL_PROFIT,
ROUND((SUM(O.PROFIT)/SUM(O.SALES)) * 100,2) AS PROFIT_MARGIN
FROM PRODUCTS P
JOIN ORDERS O 
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY CATEGORY)

SELECT 
*,
DENSE_RANK() OVER (ORDER BY TOTAL_REVENUE DESC) AS REVENUE_RANK,
DENSE_RANK() OVER (ORDER BY TOTAL_PROFIT DESC) AS PROFIT_RANK,
DENSE_RANK() OVER (ORDER BY PROFIT_MARGIN DESC) AS PROFIT_MARGIN_RANK
FROM CATEGORY_CONTRIBUTION
;